docker.sources = retailpulse-source
docker.channels = memory-channel
docker.sinks = kafka-sink

# Source
docker.sources.retailpulse-source.type = spooldir
docker.sources.retailpulse-source.spoolDir = /var/log/flume_lab/retailpulse
#docker.sources.retailpulse-source.fileSuffix = .PROCESSED
docker.sources.retailpulse-source.fileHeader = false
docker.sources.retailpulse-source.channels = memory-channel

# Memory channel
docker.channels.memory-channel.type = memory
docker.channels.memory-channel.capacity = 10000
docker.channels.memory-channel.transactionCapacity = 1000

# Kafka sink
docker.sinks.kafka-sink.type = org.apache.flume.sink.kafka.KafkaSink
docker.sinks.kafka-sink.channel = memory-channel
docker.sinks.kafka-sink.kafka.bootstrap.servers = kafka:9092
docker.sinks.kafka-sink.kafka.topic = retailpulse-events
docker.sinks.kafka-sink.kafka.flumeBatchSize = 100